# Perspektiva - měření vzdálenosti v obraze
Toto cvičení je velmi krátké a jednoduché. Nicméně, je prerekvizitou k úspěšnému absolvování druhého domácího úkolu. 

S tématem měření vzdáleností v obraze jsme se setkali již ve 3. cvičení. Připomeňme si však, jakým způsobem jsme problém řešili. Využívali jsme znalosti poměru px/mm. Tento způsob měl jednu velkou nevýhodu, neboť když se nebude obrazová rovina nacházet rovnoběžně se snímanou rovinou, poměr px/mm nebude dávat smysl a budeme dostávat chybné výsledky.

Tento problém vyřešíme znalostí perspektivy, konkrétně aplikací 2D perspektivní transformace (viz přednáška [Geometrické transformace obrazu](../../../lectures/files/bi-svz-06-metody-predzpracovani-obrazu-1.pdf) - homography). Představme si nyní obrázek, na kterém chceme zjistit skutečnou vzdálenost dvou bodů označených úsečkou **`d`**  v milimetrech.

![](pattern_measuring.jpg)

Na první pohled je jasné, že počítat poměr px/mm v tomto obraze je nesmyslné. Obraz je perspektivně zkreslený - kruhy se změnily na elipsy a obdélníky se staly lichoběžníky. Se znalostí toho, jak vypadaly původní tvary v obraze, a jaké byly jejich původní rozměry, jsme schopni papír se vzory geometricky transformovat do tvaru "kolmého k obrazové rovině". Navíc, nejenže známe velikosti referenčního oranžového obdélníku, ale známe také velikosti klasického A4 papíru (210 x 297 mm). Informace o rozměrech a tvaru papíru nám stačí k tomu, vypočítat transformační matici **`H`**, která každý pixel dokáže převést do nového "narovnaného" obrazu.

![](pattern_measuring_warped.jpg)

Pokud si v rámci této transformace ještě navíc zvolíme chytré jednotky. Výsledné vzdálenosti v pixelech budou odpovídat přímo vzdálenostem v mm nebo v čemkoliv jiném.

### Import knihoven a konfigurace

In [1]:
import numpy as np
import cv2
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

### Pomocné funkce


In [2]:
def show_images(*imgs, scale=1, window_name='Image preview'):
    """ Opens multiple image previews depending on the length of the input *imgs list.
    The preview is terminated by pressing the 'q' key.
    
    Parameters
    ----------
    *imgs : list
        Multiple input images which have to be shown.
    scale : double
        Scale of shown image window.
    window_name : Optional[string]
        An optional window name.
    Returns
    -------
    None
    """
    def print_xy(event, x, y, flags, param):
        if event == cv2.EVENT_LBUTTONDOWN:
            print('(x, y) = {}, {}'.format(x, y))
        
    for i, img in enumerate(imgs, 1):
        h,w = img.shape[:2]
        window_name_id = window_name + ' ' + str(i)
        cv2.namedWindow(window_name_id, cv2.WINDOW_NORMAL | cv2.WINDOW_GUI_NORMAL)
        cv2.resizeWindow(window_name_id, int(w * scale), int(h * scale))
        cv2.setMouseCallback(window_name_id, print_xy)
        cv2.moveWindow(window_name_id, 0, i*10)

    while 1:
        for i, img in enumerate(imgs, 1):
            cv2.imshow(window_name + ' ' + str(i), img)
            
        k = cv2.waitKey(0)
        
        if k == ord('q') or k == 27:
            break

    cv2.destroyAllWindows()

### Úkol

**1) Získejte a zobrazte si snímek fyzicky natočeného vzoru snímaného pod úhlem cca 30°.**

Nezapomínejte, že všechny kraje papíru musí být viditelné.

In [3]:
img = ...

**2) Vytvořte si dva seznamy korenspondečních bodů, které budou využity pro výpočet transformační matice H**

V prvním seznamu musí být obrazové body. K jejich získáni využijte implementovaný callback ve funkci `show_images`, který po kliknutí do obrazu, vypíše souřadnice.
Druhý seznam musí obsahovat cílové souřadnice bodů, do kterých chceme vybrané body z prvního seznamu transformovat. 

Pozor, záleží na pořadí bodů a obě struktury musí být `np.array`.


In [4]:
image_pts = ...
world_pts = ...

**3) Pomocí funkce [`cv2.findHomography`](https://docs.opencv.org/3.4.1/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780) získejte transformační matici `H`. Matici vypiště, ať si připomenete její tvar.**

In [5]:
H, mask = ...

[[0.895 -1.463 1924.333]
 [0.819 1.827 -2900.061]
 [-0.000 0.000 1.000]]


**4) Využijte [`cv2.warpPerspective`](https://docs.opencv.org/3.4.1/da/d54/group__imgproc__transform.html#gaf73673a7e8e18ec6963e3774e6a94b87), která přijímá transformační matici `H`, k narovnání zdrojového obrazu. Výsledek zobrazte.** 

In [6]:
warped_img = ...

**5) Ve vašem nasnímaném obraze získejte souřadnice hraničnich bodů úsečky `d` a uložte je do definovaných proměných.** 

Nelekejte se zběsilého předepsaného formátu, OpenCV bohužel občas požaduje zvláštní struktury.

In [ ]:
...

In [7]:
pt_src = np.array([[(...)]], dtype='float32')
pt_dst = np.array([[(...)]], dtype='float32')

**6) Využijte [`cv2.perspectiveTransform`](https://docs.opencv.org/3.4.1/d2/de8/group__core__array.html#gad327659ac03e5fd6894b90025e6900a7) k transformaci zdrojových bodů do nového prostoru a vypočítejte reálnou vzdálenost, kterou vypište.**

In [8]:
pt_t_src = ...
pt_t_dst = ...

dist = ...
print(f'D = {dist / 10:.02f} mm')

D = 158.05 mm
